=== andrew-303/interfacetesthog01/src/main/resources/com/hogwarz/interfacetest/testcase/user_get_schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://example.com/root.json",
  "type": "object",
  "title": "The Root Schema",
  "required": [
    "errcode",
    "errmsg",
    "userid",
    "name",
    "department",
    "position",
    "mobile",
    "gender",
    "email",
    "avatar",
    "status",
    "isleader",
    "extattr",
    "telephone",
    "enable",
    "hide_mobile",
    "order",
    "qr_code",
    "alias",
    "is_leader_in_dept",
    "address",
    "thumb_avatar"
  ],
  "properties": {
    "errcode": {
      "$id": "#/properties/errcode",
      "type": "integer",
      "title": "The Errcode Schema",
      "default": 0,
      "examples": [
        0
      ]
    },
    "errmsg": {
      "$id": "#/properties/errmsg",
      "type": "string",
      "title": "The Errmsg Schema",
      "default": "",
      "examples": [
        "ok"
      ],
      "pattern": "^(.*)$"
    },
    "userid": {
      "$id": "#/properties/userid",
      "type": "string",
      "title": "The Userid Schema",
      "default": "",
      "examples": [
        "Biyl_1578552417150"
      ],
      "pattern": "^(.*)$"
    },
    "name": {
      "$id": "#/properties/name",
      "type": "string",
      "title": "The Name Schema",
      "default": "",
      "examples": [
        "The First Member"
      ],
      "pattern": "^([0-9]*)$"
    },
    "department": {
      "$id": "#/properties/department",
      "type": "array",
      "title": "The Department Schema",
      "items": {
        "$id": "#/properties/department/items",
        "type": "integer",
        "title": "The Items Schema",
        "default": 0,
        "examples": [
          3
        ]
      }
    },
    "position": {
      "$id": "#/properties/position",
      "type": "string",
      "title": "The Position Schema",
      "default": "",
      "examples": [
        ""
      ],
      "pattern": "^(.*)$"
    },
    "mobile": {
      "$id": "#/properties/mobile",
      "type": "string",
      "title": "The Mobile Schema",
      "default": "",
      "examples": [
        "15785524171"
      ],
      "pattern": "^(.*)$"
    },
    "gender": {
      "$id": "#/properties/gender",
      "type": "string",
      "title": "The Gender Schema",
      "default": "",
      "examples": [
        "0"
      ],
      "pattern": "^(.*)$"
    },
    "email": {
      "$id": "#/properties/email",
      "type": "string",
      "title": "The Email Schema",
      "default": "",
      "examples": [
        ""
      ],
      "pattern": "^(.*)$"
    },
    "avatar": {
      "$id": "#/properties/avatar",
      "type": "string",
      "title": "The Avatar Schema",
      "default": "",
      "examples": [
        ""
      ],
      "pattern": "^(.*)$"
    },
    "status": {
      "$id": "#/properties/status",
      "type": "integer",
      "title": "The Status Schema",
      "default": 0,
      "examples": [
        4
      ]
    },
    "isleader": {
      "$id": "#/properties/isleader",
      "type": "integer",
      "title": "The Isleader Schema",
      "default": 0,
      "examples": [
        0
      ]
    },
    "extattr": {
      "$id": "#/properties/extattr",
      "type": "object",
      "title": "The Extattr Schema",
      "required": [
        "attrs"
      ],
      "properties": {
        "attrs": {
          "$id": "#/properties/extattr/properties/attrs",
          "type": "array",
          "title": "The Attrs Schema"
        }
      }
    },
    "telephone": {
      "$id": "#/properties/telephone",
      "type": "string",
      "title": "The Telephone Schema",
      "default": "",
      "examples": [
        ""
      ],
      "pattern": "^(.*)$"
    },
    "enable": {
      "$id": "#/properties/enable",
      "type": "integer",
      "title": "The Enable Schema",
      "default": 0,
      "examples": [
        1
      ]
    },
    "hide_mobile": {
      "$id": "#/properties/hide_mobile",
      "type": "integer",
      "title": "The Hide_mobile Schema",
      "default": 0,
      "examples": [
        0
      ]
    },
    "order": {
      "$id": "#/properties/order",
      "type": "array",
      "title": "The Order Schema",
      "items": {
        "$id": "#/properties/order/items",
        "type": "integer",
        "title": "The Items Schema",
        "default": 0,
        "examples": [
          0
        ]
      }
    },
    "qr_code": {
      "$id": "#/properties/qr_code",
      "type": "string",
      "title": "The Qr_code Schema",
      "default": "",
      "examples": [
        "https://open.work.weixin.qq.com/wwopen/userQRCode?vcode=vcf5913654e4b1be65"
      ],
      "pattern": "^(.*)$"
    },
    "alias": {
      "$id": "#/properties/alias",
      "type": "string",
      "title": "The Alias Schema",
      "default": "",
      "examples": [
        ""
      ],
      "pattern": "^(.*)$"
    },
    "is_leader_in_dept": {
      "$id": "#/properties/is_leader_in_dept",
      "type": "array",
      "title": "The Is_leader_in_dept Schema",
      "items": {
        "$id": "#/properties/is_leader_in_dept/items",
        "type": "integer",
        "title": "The Items Schema",
        "default": 0,
        "examples": [
          0
        ]
      }
    },
    "address": {
      "$id": "#/properties/address",
      "type": "string",
      "title": "The Address Schema",
      "default": "",
      "examples": [
        "?????2-6?"
      ],
      "pattern": "^(.*)$"
    },
    "thumb_avatar": {
      "$id": "#/properties/thumb_avatar",
      "type": "string",
      "title": "The Thumb_avatar Schema",
      "default": "",
      "examples": [
        ""
      ],
      "pattern": "^(.*)$"
    }
  }
}

=== andrew-303/interfacetesthog01/src/main/resources/com/hogwarz/interfacetest/api/user.json
{
  "errcode": 0,
  "errmsg": "ok",
  "userid": "{{userid}}",
  "name": "{{name}}",
  "department": [
    3
  ],
  "position": "",
  "mobile": "{{mobile}}",
  "gender": "0",
  "email": "",
  "avatar": "",
  "status": 4,
  "isleader": 0,
  "extattr": {
    "attrs": [

    ]
  },
  "telephone": "",
  "enable": 1,
  "hide_mobile": 0,
  "order": [
    0
  ],
  "qr_code": "https://open.work.weixin.qq.com/wwopen/userQRCode?vcode=vcf5913654e4b1be65",
  "alias": "",
  "is_leader_in_dept": [
    0
  ],
  "address": "杭州",
  "thumb_avatar": ""
}
